Revert "Add `--no-headers` for k alias"
This reverts commit 9011c06e4293e6ee2fa4bdb08cd8d6e32872c28d.

```console
k images --all-namespaces --output-format json | jq -r '.[] | .image' | sort -u | rg -v '[0-1]*.dkr|[0-1]*.dkr'
Error: flags cannot be placed before plugin name: --no-headers
```