machines/work/home/packages: disable kcat due to avro-c++ build failure
The kcat package fails to build due to its dependency avro-c++ being
incompatible with fmt 11.2.0. Commenting out until nixpkgs updates
avro-c++ with fmt 11 compatibility.

Full build error:

avro-c++> make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/avrocpp.dir/all] Error 2
avro-c++> make: *** [Makefile:166: all] Error 2
error: builder for '/nix/store/1283wvz9bzlwbdy82q525n6n7p30ynfa-avro-c++-1.12.0.drv' failed with exit code 2;
       last 25 log lines:
       > In file included from /nix/store/62zqa5mmjqf61bgzgjv1r7im1f0c36ip-fmt-11.2.0-dev/include/fmt/format.h:41:
       > /nix/store/62zqa5mmjqf61bgzgjv1r7im1f0c36ip-fmt-11.2.0-dev/include/fmt/base.h:2275:23: error: no matching member function for call to 'format'
       >  2275 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
       >       |                    ~~~^~~~~~
       > /nix/store/62zqa5mmjqf61bgzgjv1r7im1f0c36ip-fmt-11.2.0-dev/include/fmt/base.h:2255:21: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::format_custom<avro::Type, fmt::formatter<avro::Type>>' requested here
       >  2255 |     custom.format = format_custom<value_type, formatter<value_type, char_type>>;
       >       |                     ^
       > /nix/store/62zqa5mmjqf61bgzgjv1r7im1f0c36ip-fmt-11.2.0-dev/include/fmt/format.h:4201:40: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::value<avro::Type, 0>' requested here
       >  4201 |   return vformat(fmt.str, vargs<T...>{{args...}});
       >       |                                        ^
       > /private/tmp/nix-build-avro-c++-1.12.0.drv-0/avro-cpp-1.12.0/include/avro/Exception.hh:37:35: note: in instantiation of function template specialization 'fmt::format<avro::Type>' requested here
       >    37 |         : std::runtime_error(fmt::format(fmt, std::forward<Args>(args)...)) {}
       >       |                                   ^
       > /private/tmp/nix-build-avro-c++-1.12.0.drv-0/avro-cpp-1.12.0/impl/ValidSchema.cc:38:15: note: in instantiation of function template specialization 'avro::Exception::Exception<avro::Type>' requested here
       >    38 |         throw Exception("Schema is invalid, due to bad node of type {}", node->type());
       >       |               ^
       > /private/tmp/nix-build-avro-c++-1.12.0.drv-0/avro-cpp-1.12.0/include/avro/Types.hh:116:10: note: candidate function template not viable: 'this' argument has type 'const fmt::formatter<avro::Type>', but method is not marked const
       >   116 |     auto format(avro::Type t, FormatContext &ctx) {
       >       |          ^
       > 2 errors generated.
       > make[2]: *** [CMakeFiles/avrocpp_s.dir/build.make:177: CMakeFiles/avrocpp_s.dir/impl/ValidSchema.cc.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/avrocpp_s.dir/all] Error 2

Dependency chain: kcat → libserdes → avro-c++