Revert "Add `--no-headers` for k alias"
This reverts commit 12eee6928f6ab32bf079d70291c2fb0cd2f05567.

```console
k images --all-namespaces --output-format json | jq -r '.[] | .image' | sort -u | rg -v '[0-1]*.dkr|[0-1]*.dkr'
Error: flags cannot be placed before plugin name: --no-headers
```