Revert "machines/servers/http: use replaceVars instead of substituteAll"
This reverts commit bec02eeb182ecfbe8237e4b36d8ecf7d3f38a3b2.

Both bee and mini are on release versions, so will handle that later on.

```console
  /nix/store/brn6sx5n1acx4w2jsq5h2ac365kz5nvc-caddyfile.drv
  /nix/store/bsiyq7r3fk2lm9bhq4kf35qd8az2b9qj-caddy-starter.drv
  /nix/store/zc77qgbx675nyb7f9h8ih1x1nn45prxh-org.nixos.caddy.plist.drv
  /nix/store/5v1wkgmbbafw4pla4b3krylijvpj4rbq-launchd.drv
  /nix/store/dv8qf35q744zkc4p8h9qcmfdlyl37z7h-darwin-system-24.11.fc84389.drv
building '/nix/store/brn6sx5n1acx4w2jsq5h2ac365kz5nvc-caddyfile.drv'...
caddyfile> /private/tmp/nix-build-caddyfile.drv-0/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 1: replaceVars: command not found
error: builder for '/nix/store/brn6sx5n1acx4w2jsq5h2ac365kz5nvc-caddyfile.drv' failed with exit code 127;
       last 1 log lines:
       > /private/tmp/nix-build-caddyfile.drv-0/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 1: replaceVars: command not found
       For full logs, run:
         nix log /nix/store/brn6sx5n1acx4w2jsq5h2ac365kz5nvc-caddyfile.drv
error: 1 dependencies of derivation '/nix/store/bsiyq7r3fk2lm9bhq4kf35qd8az2b9qj-caddy-starter.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zc77qgbx675nyb7f9h8ih1x1nn45prxh-org.nixos.caddy.plist.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5v1wkgmbbafw4pla4b3krylijvpj4rbq-launchd.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dv8qf35q744zkc4p8h9qcmfdlyl37z7h-darwin-system-24.11.fc84389.drv' failed to build
```